name: Deploy Resume PDF to S3

on:
  push:
    branches:
      - main
    paths:
      - 'resume/resume.pdf'

jobs:
  sync-resume-pdf:
    name: Upload Resume PDF to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: mx-central-1 

      - name: Upload resume PDF to S3
        run: |
          aws s3 cp resume/resume.pdf s3://${{ secrets.RESUME_BUCKET_DESTINATION }}